lagom/online-auction-java

bidding-impl/src/main/java/com/example/auction/bidding/impl/AuctionEvent.java
bidding-impl/src/main/java/com/example/auction/bidding/impl/AuctionScheduler.java
bidding-impl/src/main/java/com/example/auction/bidding/impl/BiddingServiceImpl.java
item-impl/src/main/java/com/example/auction/item/impl/ItemServiceImpl.java
item-impl/src/main/java/com/example/auction/item/impl/PItemEvent.java

This brings it up to date with the changes from lagom/lagom#176.

Update to use AggregateEventShards

---

README.md
build.sbt
item-api/src/main/java/com/example/auction/item/api/ItemService.java
item-api/src/main/java/com/example/auction/item/api/ItemSummary.java
item-api/src/main/java/com/example/auction/item/api/PaginatedSequence.java
item-impl/src/main/java/Module.java
item-impl/src/main/java/com/example/auction/item/impl/CompletionStageUtils.java
item-impl/src/main/java/com/example/auction/item/impl/ItemRepository.java
item-impl/src/main/java/com/example/auction/item/impl/ItemServiceImpl.java
item-impl/src/main/java/com/example/auction/item/impl/PItemStatus.java
web-gateway/app/assets/main.css
web-gateway/app/controllers/Main.java
web-gateway/app/controllers/ProfileController.java
web-gateway/app/views/main.scala.html
web-gateway/app/views/myItems.scala.html
web-gateway/app/views/paginate.scala.html
web-gateway/conf/messages
web-gateway/conf/routes

- Add a Cassandra read side processor for `PItemEvent`s that allows for querying by creator and status.
- Create a profile UI in the web gateway for displaying the current user's item in each status.
- Implement the service call.

Implement getItemsForUser

---

bidding-impl/src/main/java/com/example/auction/bidding/impl/AuctionCommand.java
bidding-impl/src/main/java/com/example/auction/bidding/impl/AuctionEvent.java
bidding-impl/src/main/java/com/example/auction/bidding/impl/AuctionScheduler.java
bidding-impl/src/main/java/com/example/auction/bidding/impl/AuctionState.java
bidding-impl/src/main/java/com/example/auction/bidding/impl/BidValidationException.java
build.sbt
project/plugins.sbt

There's still one issue with Eclipse we should address after this is merged. See https://github.com/lagom/lagom/issues/396

Improved Eclipse setup and fix compilation warnings

---

bidding-impl/src/main/java/com/example/auction/bidding/impl/AuctionEntity.java
bidding-impl/src/test/java/com/example/auction/bidding/impl/AuctionEntityTest.java

Add a simple if statement in AuctionEntity.java that checks whether the current Bid price is over the reserve which fixes issue #29. Add 3 tests in AuctionEntityTest to check whether the system gives correct results when a bidder increments their bid from a value bellow the reserve to a value over the reserve, from bellow the reserve to bellow and from over the reserve to over the reserve.

fix bug #29 and create 3 test cases

---

web-gateway/conf/messages

Fixes #31 Add i18n values for validation error keys

---

README.md

Fixes #28 and take one step toward #38

Add importing steps for IDEA and Eclipse in README

---

project/plugins.sbt

Upgrade lagom-sbt-plugin to 1.3.0

---

web-gateway/app/controllers/Currency.java
web-gateway/app/controllers/ItemForm.java

Japanese currency doesn't use decimal places (currency.getDefaultFractionDigits() returns 0). In this case the step should be 1.
Fixes #30

Small fix for bug #30

---

README.md

Add sbt installation in readme

---

build.sbt

Port of lagom/online-auction-scala#32 by @yg-apaza.

Compile the project before generating Eclipse files

---

web-gateway/app/views/createUser.scala.html
web-gateway/conf/messages

Hi, I am Mehul Smriti Raje, intending to apply for Outreachy 14 with Lagom. 
Adding fix for #56  
Is this the correct way to add the inline instruction or do we want a placeholder text?

Issue #56: Added inline instruction for creating new user.

---

web-gateway/app/views/editItem.scala.html
web-gateway/app/views/myItems.scala.html
web-gateway/conf/messages

Added fix for Issue 58: Instructions to edit items

---

.travis.yml

Use ES deb installers in Travis

---

web-gateway/app/views/createUser.scala.html
web-gateway/app/views/editItem.scala.html
web-gateway/app/views/myItems.scala.html
web-gateway/conf/messages

Changed inline instructions to create users and edit items in message.config to match naming conventions. Updated the references to these instructions.

Modified instructions in message.config

---

web-gateway/app/controllers/ItemController.java
web-gateway/app/controllers/Main.java
web-gateway/app/controllers/ProfileController.java
web-gateway/app/controllers/SearchController.java
web-gateway/app/views/createItem.scala.html
web-gateway/app/views/createUser.scala.html
web-gateway/app/views/editItem.scala.html
web-gateway/app/views/item.scala.html
web-gateway/app/views/myItems.scala.html
web-gateway/app/views/searchItem.scala.html
web-gateway/conf/application.conf

Added flag for inline instructions

---

bidding-impl/src/main/resources/application.conf
item-impl/src/main/resources/application.conf
user-impl/src/main/resources/application.conf

https://github.com/lagom/lagom/issues/578

Add Cassandra keyspace configuration

---

README.md
build.sbt
docs/running-in-conductr.md
project/plugins.sbt
search-api/src/main/java/com/example/auction/search/api/SearchService.java

Also includes fixes for a few minor ConductR compatibility issues.

Add instructions for running in ConductR

---

README.md

Update links of Lagom template using maven and sbt

---

README.md

Looks like it needed updating.

Fix link in 'Running in Production Mode' section of README.md

---

bidding-impl/src/test/java/com/example/auction/bidding/impl/AuctionEntityTest.java
build.sbt
transaction-api/src/main/java/com/example/auction/transaction/api/DeliveryInfo.java
transaction-api/src/main/java/com/example/auction/transaction/api/TransactionInfo.java
transaction-api/src/main/java/com/example/auction/transaction/api/TransactionService.java
transaction-impl/src/main/java/Module.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/Transaction.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionCommand.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEntity.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEvent.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionServiceImpl.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionState.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionStatus.java
transaction-impl/src/main/resources/application.conf
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionEntityTest.java

Use Case 2: As an auction winner I want to init the transaction after the auction finished

[WIP] Set up Transaction Service

---

build.sbt
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionServiceImpl.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionEntityTest.java

- Basic test for start transaction
- Add transaction service to root project

Test for start transaction

---

user-impl/src/main/java/com/example/auction/user/impl/Mappers.java
user-impl/src/main/java/com/example/auction/user/impl/PUser.java
user-impl/src/main/java/com/example/auction/user/impl/UserCommand.java
user-impl/src/main/java/com/example/auction/user/impl/UserEntity.java
user-impl/src/main/java/com/example/auction/user/impl/UserEvent.java
user-impl/src/main/java/com/example/auction/user/impl/UserServiceImpl.java
web-gateway/app/controllers/CreateUserForm.java
web-gateway/app/views/createUser.scala.html
web-gateway/conf/messages

-  Update the "Create User" form to include email, password and verify password fields 
-  Show an error if the password and verify password fields don't match

 Add email , password and confirm password fields to create user form

---

user-api/src/main/java/com/example/auction/user/api/User.java
user-api/src/main/java/com/example/auction/user/api/UserRegistration.java
user-api/src/main/java/com/example/auction/user/api/UserService.java
user-impl/src/main/java/com/example/auction/user/impl/Mappers.java
user-impl/src/main/java/com/example/auction/user/impl/PUser.java
user-impl/src/main/java/com/example/auction/user/impl/UserCommand.java
user-impl/src/main/java/com/example/auction/user/impl/UserEntity.java
user-impl/src/main/java/com/example/auction/user/impl/UserServiceImpl.java
web-gateway/app/controllers/Main.java

- Add `email` to `User` of api
- Add `UserRegisteration` to seperate registration details

Add UserRegisteration class to seperate registration details

---

project/build.properties

bump sbt version.

---

README.md

This is just a start at improving the readme and docs for online auction.

Work on readme

---

build.sbt
item-impl/src/test/java/com/example/auction/item/impl/ItemEventProcessorTest.java
tools/src/test/java/com/example/core/ReadSideTestDriver.java

Move ReadSideTestDriver to tools project

---

web-gateway/app/controllers/ItemController.java
web-gateway/app/controllers/Main.java
web-gateway/app/controllers/ProfileController.java
web-gateway/app/controllers/SearchController.java
web-gateway/conf/application.conf

This applies changes from https://github.com/lagom/online-auction-java/pull/100 which are compatible with Lagom 1.3 so that final upgrade to Lagom 1.4 is as small as possible.

Upgrade code to make compatible with Lagom 1.4

---

transaction-api/src/main/java/com/example/auction/transaction/api/TransactionInfo.java
transaction-api/src/main/java/com/example/auction/transaction/api/TransactionService.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/Transaction.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionCommand.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEntity.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEvent.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionServiceImpl.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionState.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionEntityTest.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionServiceImplIntegrationTest.java
web-gateway/src/main/java/controllers/DeliveryPriceForm.java
web-gateway/src/main/java/controllers/TransactionController.java
web-gateway/src/main/resources/messages
web-gateway/src/main/resources/routes
web-gateway/src/main/twirl/views/deliveryDetails.scala.html
web-gateway/src/main/twirl/views/deliveryPrice.scala.html
web-gateway/src/main/twirl/views/myTransactions.scala.html
web-gateway/src/main/twirl/views/transaction.scala.html

Fixes #136 
Also addresses the last task of #107
UI

Set delivery price

---

user-impl/src/test/java/com/example/auction/user/impl/UserServiceImplTest.java

Use testkit project in UserServiceImplTest

---

user-api/src/main/java/com/example/auction/user/api/User.java
user-impl/src/main/java/com/example/auction/user/impl/Mappers.java
user-impl/src/main/java/com/example/auction/user/impl/PUser.java
user-impl/src/main/java/com/example/auction/user/impl/PUserEntity.java
user-impl/src/main/java/com/example/auction/user/impl/UserRepository.java
user-impl/src/main/java/com/example/auction/user/impl/UserServiceImpl.java
user-impl/src/test/java/com/example/auction/user/impl/UserEntityTest.java
user-impl/src/test/java/com/example/auction/user/impl/UserRepositoryTest.java
web-gateway/src/main/java/controllers/AbstractController.java

Fixes #141 
- createdAt field is removed from UserInfo
- UserInfo can now fetch its first page

 Remove createdAt from user

---

transaction-api/src/main/java/com/example/auction/transaction/api/TransactionInfoStatus.java
transaction-api/src/main/java/com/example/auction/transaction/api/TransactionService.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionCommand.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEntity.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEvent.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionMappers.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionRepository.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionServiceImpl.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionState.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionStatus.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionEntityTest.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionRepositoryTest.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionServiceImplIntegrationTest.java
web-gateway/src/main/java/controllers/AbstractController.java
web-gateway/src/main/java/controllers/TransactionController.java
web-gateway/src/main/resources/messages
web-gateway/src/main/resources/routes
web-gateway/src/main/twirl/views/transaction.scala.html

After submitting delivery details and price, the seller should approve it, so the buyer can pay after.

Add Payment pending status

---

item-api/src/main/java/com/example/auction/item/api/Location.java
transaction-api/src/main/java/com/example/auction/transaction/api/PaymentInfo.java
transaction-api/src/main/java/com/example/auction/transaction/api/TransactionInfo.java
transaction-api/src/main/java/com/example/auction/transaction/api/TransactionService.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/Payment.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/Transaction.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionCommand.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEntity.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEvent.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionMappers.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionRepository.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionServiceImpl.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionState.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionEntityTest.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionRepositoryTest.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionServiceImplIntegrationTest.java

As a buyer, I want to submit payment details of the item

---

transaction-impl/src/main/java/Module.java

Use gracefulShutdown in transaction service

---

transaction-api/src/main/java/com/example/auction/transaction/api/PaymentInfoStatus.java
transaction-api/src/main/java/com/example/auction/transaction/api/TransactionInfoStatus.java
transaction-api/src/main/java/com/example/auction/transaction/api/TransactionService.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/PaymentStatus.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionCommand.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEntity.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionEvent.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionMappers.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionRepository.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionServiceImpl.java
transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionStatus.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionEntityTest.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionRepositoryTest.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionServiceImplIntegrationTest.java

Add feature on Transaction Service: Submit payment status (approved/rejected)

---

web-gateway/src/main/java/controllers/TransactionController.java
web-gateway/src/main/resources/messages
web-gateway/src/main/resources/routes
web-gateway/src/main/twirl/views/transaction.scala.html

Here is how it looks for the seller after the buyer has submitted the payment details

Add UI for approve or reject payment

---

project/build.properties

Update sbt to 0.13.16

---

bidding-impl/src/test/java/com/example/auction/bidding/impl/AuctionEntityTest.java
item-impl/src/test/java/com/example/auction/item/impl/ItemEntityTest.java
transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionEntityTest.java
user-impl/src/test/java/com/example/auction/user/impl/UserEntityTest.java

Replace deprecated JavaTestKit with current equivalent
